mypractice/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('practice.urls')),
    path('admin/', admin.site.urls),
]

practice/urls.py
from django.urls import path
from . import views

app_name = "practice"

urlpatterns = [
    path('', views.index, name='index')
]

practice/models.py
from django.db import models


# Create your models here.
class State(models.Model):
    state_text = models.CharField(max_length=50)
    create_date = models.DateTimeField('date created')

    def __str__(self):
        return self.state_text


class Capital(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    capital_text = models.CharField(max_length=50)
    # tribe = models.CharField(max_length=40)

    def __str__(self):
        return self.capital_text


class Region(models.Model):
    region = models.ForeignKey(State, on_delete=models.CASCADE)
    region_text = models.CharField(max_length=50)

    def __str__(self):
        return self.region_text


class Tribe(models.Model):
    tribe = models.ForeignKey(State, on_delete=models.CASCADE)
    tribe_text = models.CharField(max_length=50)

    def __str__(self):
        return self.tribe_text

practice/views.py
from django.shortcuts import render
from .models import State


# Create your views here.
def index(request):
    states = State.objects.all()
    context = {
        "states": states
    }
    return render(request, "practice/index.html", context)

practice/templates/practice/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>States and Capitals of Nigeria 2021</title>
</head>
<body>
{% block content %}
    <ol>
    {% for state in states %}
    <li>
        <p>{{ state.state_text }}</p>
        <ol>
            {% for capital in state.capital_set.all %}
            <li>{{ capital.capital_text }}</li>
            {% endfor %}
        </ol>
        <ol>
            {% for region in state.region_set.all %}
                <li>{{ region.region_text }}</li>
            {% endfor %}
        </ol>
        <ol>
            {% for tribe in state.tribe_set.all %}
            <li>{{ tribe.tribe_text }}</li>
            {% endfor %}
        </ol>
    </li>
    {% endfor %}
    </ol>
{% endblock content %}
</body>
</html>